services:
  mysql:
    image: mysql:8.0
    container_name: game-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game
    ports:
      - "3306:3306"
  redis:
    image: redis:7.2.4
    container_name: game-redis
    restart: always
    ports:
      - "6379:6379"